function  solve_1D_DD_IPDG(mo,k)
% use to solve drift-diffusion model,has 2 equations
% the main task is to solve the first equation
% the second equation is solved by solve_poisson_1D_FEM.m
% n_{t} - (\mu*E*n)_{x} = \tau*\theta*n_{xx}
% \phi_{xx} = e/{\epsilon}*(n - nd)
% where unknown are n,phi and E=-phi_x
% n Periodic \phi dirichlet \phi(0,t)=0;\phi(1,t)=vbias
% k:Used in conjunction with the calculation of the error order(check_error_1D.m)
% mo:order of polynomial space

if nargin < 1
    k = 1;
    mo= 2;
elseif nargin < 2
    k = 1;
end

%% 参数
% left,right:boundary
% emg:Convection velocity, the coefficient of the convection term
% emf:diffusion velocity,the coefficient of the diffusion term
% T_end:the last moment in time
% ng:num grids
% mp:hightest order of polynomial
% mt:Choose between RK3 and RK4 (mt = 3 for RK3, mt = 4 for RK4)

format long;
% struct parameter for DD
% Contains some constant term parameters, only need to run one time
% params = struct('xk', 0.138046e-4, 'epsilon', 11.7*8.85418,'xe', 0.1602,'xm',0.26*0.9109,'T_0',300,'xmu',0.75); % 创建参数结构
% save('params.mat', 'params'); 
% boundary = struct('xk',0.138046e-4,'T_0',300,'xe',0.1602,'ni',0.014,'vbias',1.5);
% save('boundary.mat', 'boundary');

left = 0;
right = 0.6;
emg = convecion_diffusion_coefficient('DD',11);
emf = convecion_diffusion_coefficient('DD',12);
T_end = 1;
ng = 20*2^(k-1);
mp = mo-1;
mt = 3;

% trial/test_basis_type: trial/test function's basis type
% ==101:orthogonal legendre basis with highest order's coefficient is 1
test_basis_type = 101;
trial_basis_type = 101;

%% Gauss-lobatto and reference matrix(legendre & [-0.5,0.5])
% refernce matrix could only ues in constant coefficient term, if term has
% variable coefficient then it needs to use Gauss quadrature method in local.
% GP_r:Gauss ponits in [-0.5,0.5]
% GW_r:Gauss quadrature weights in [-0.5,0.5]
% Gauss_coefficient(:,1)==GP_r;Gauss_coefficient(:,2)==GW_r;
% a:inverse of mass matrix evaluate the basis in [-0.5,0.5]
% b:stiffness matrix evaluate the basis in [-0.5,0.5]
% c:evaluate inner product (u1,u1x). Since in this problem this term has
% variable coefficient, we just compute directly on the local function.
% d:evaluate basis fun mutiply on the boundary with derivative 0,and d is a
% 4-element set which shape is (mp+1,mp+1,4) 
% e:evaluate basis fun mutiply on the boundary with derivative 1,and e is a
% 4-element set which shape is (mp+1,mp+1,4) 

Gauss_coefficient = generate_1D_gaussian_quadrature_r(mp);

% after the first evaluation, can save the result in txt, this part is
% independent from other work,such like use Gauss quadrature formula
a = generate_1D_matrix_r(Gauss_coefficient,mp,mp,trial_basis_type,0,test_basis_type,0);
b = generate_1D_matrix_r(Gauss_coefficient,mp,mp,trial_basis_type,1,test_basis_type,1);
c = generate_1D_matrix_r(Gauss_coefficient,mp,mp,trial_basis_type,0,test_basis_type,1);
d = generate_1D_boundary_multiple(mp,trial_basis_type,0,test_basis_type,0);
e = generate_1D_boundary_multiple(mp,trial_basis_type,1,test_basis_type,0);
f = generate_1D_boundary_multiple(mp,trial_basis_type,0,test_basis_type,1);

%% Segment & related coefficients
% P_partition:剖分节点坐标,size is (1,ng+1)
% T_partition:剖分索引,size is (2,ng)
% T_partition(1,*):left point of the *th segment
% T_partition(2,*):right point of the *th segment
% h:max_diam(S_h), where S_h is the space of segment
% theta: interior penalty coefficient in IPDG method

% DD model need to non-uniform partition, because nd is not a constant
% which has a rapid but smooth change.

[P_partition,T_partition] = generate_grid_1D(left,right,ng);
h = max(diff(P_partition));
% C_penalty:penalty coefficient of IPDG, The larger the better, but too large leads to unstable solutions
% and the maximum value is related to mp:For mp=1, C_penalty=2; for mp=2, C_penalty=10; for mp=3, C_penalty=22
if mp == 1
   C_penalty = 2;
elseif mp == 2
    C_penalty = 10;
elseif mp == 3
    C_penalty = 22;
end
theta = C_penalty/h;

%% initial condition with L2-projection
% n0：the initial discrete value of unknow variable n
% use the second equation, could compute the initial value of \phi
% to solve the second equation, i use standard FEM method

n0 = L2_projection_1D('initial_condition',a,ng,mp,P_partition,T_partition);
% plot_solution('initial_condition',0,uh0,ng,mp,P_partition,T_partition)
% error1 = evaluate_error_Lnorm('initial_condition',1,0,uh0,ng,mp,P_partition,T_partition)

%% evaluate the first equation left terms & right terms
% left terms:generate coefficient of the unknown variables
% M1 is generated by diffusion, usually the inv(mass_matrix)*stiffness_matrix
% M2 is generated by convection, here is variable coefficient
% consider interior boundaries, it could influent neighbouring section, so we use R,L,H to express these situations.
% R1,L1,H1:generate by convection;R2,L2,H2:generate by diffusion
% flux函数只负责生成间断项，参数里含11的是convection生成的，一般不含导数项；参数里含12的是diffusion生成的，一般带导数项
% 由于使用的是参考单元上的基函数，带导数的需要除以h_local转换到局部单元上。
% 由于IPDG有时需要让结构具有对称性，这里生成对称项，同时对称项正负由\alpha(1或-1)决定
% 一会检查一下是否都是正的
% Note that all matrices below are preceded by +, if - need to add before the function

inv_a = inv(a);
alpha = 1;

M1 = generate_1D_convection_diffusion_matrix_local(inv_a,b,c,ng,mp,mp,P_partition,T_partition,12);
[H1,R1,L1] = generate_1D_convection_diffusion_flux_local(inv_a,d,e,ng,mp,P_partition,T_partition,12);
[H2,R2,L2] = generate_1D_symmetrical_local(inv_a,f,ng,mp,P_partition,T_partition);
[H3,R3,L3] = generate_1D_penalty_local(inv_a,d,theta,ng,mp,P_partition,T_partition);

M = emf*M1;
H = emf*(-H1-alpha*H2+H3);
R = emf*(-R1-alpha*R2+R3);
L = emf*(-L1-alpha*L2+L3);

A_without_T = assemble_1D_matrix_without_variable(M,H,R,L,ng,mp);

% right terms:involving all known value
% evaluate b = (f,v)
% 如果使用Rk显式迭代，直接在time_evoulation_with_RK里面生成
% 这里有问题，需要考虑除以质量矩阵，但是这个问题右端为0不需要改
% rs = generate_1D_vector("f1_fun",Gauss_coefficient,ng,mp,P_partition,T_partition);

%% time evoulation
% choose CFL condition
cflc = generate_cfl_condition(mp,11);
cfld = generate_cfl_condition(mp,12);
dt = evaluate_dt(cflc,cfld,emg,emf,P_partition,T_partition);

% Runge-Kutta scheme for advancing in time
% solute uht = f(uh) = -A*uh + b
[uh_list,t_list] = time_evoulation_with_RK_variable_coefficient(Gauss_coefficient,A_without_T,inv_a,d,T_end,n0,dt,mp,mt,P_partition,T_partition,trial_basis_type,test_basis_type);
%% evaluate error(involving L1,L2,L\infinite)
% 
% error1 = evaluate_error_Lnorm('exact_fun',1,t_list(end),uh_list(:,end),ng,mp,P_partition,T_partition);
% error2 = evaluate_error_Lnorm('exact_fun',2,t_list(end),uh_list(:,end),ng,mp,P_partition,T_partition);
% errorf = evaluate_error_absolute('exact_fun',t_list(end),uh_list(:,end),P_partition,T_partition,ng,mp);
% 
% error=[error1,error2,errorf];
% plot_solution('exact_fun',t_list(end),uh_list(:,end),ng,mp,P_partition,T_partition)
uh_list