function result = generate_1D_variable_coefficient_matrix_local(coefficient_fun,inv_a,Gauss_coefficient,P,T,trial_basis_type,trial_derivative,test_basis_type,test_derivative,Tb,uh)
% Output matrix with variable coefficient
% variable coefficient has 2 different situation:
% 1)a(x,t) is a known function that can use directly
% 2)uh(x,t) is also an unknown quantity that needs to be generated by summing the basis functions

mp = size(Tb,1)-1;
ng = length(T);
result = zeros(mp+1,mp+1,ng);
Gp = Gauss_coefficient(:,1);
Gw = Gauss_coefficient(:,2);
Gpn = length(Gw);

for n = 1:ng

    mesh_nodes = P(:,T(:,n));
    h_local = max(mesh_nodes)-min(mesh_nodes);
    uh_local = uh(Tb(:,n));

    E = feval(coefficient_fun,Gp,uh_local,trial_basis_type,1)*h_local^(-1);

    for i = 0:mp
        % test(i)
        for j = 0:mp
            % trial(j)
            for k = 1:Gpn
                % DD model needs to compute E, but E is -\phi_x, so let
                % derivative is 1，这里也是可以完善到输入里面                   
                result(i+1,j+1,n) = result(i+1,j+1,n) + Gw(k)*feval(coefficient_fun,Gp(k),uh_local,trial_basis_type,1)*h_local^(-1)...
                                                        *reference_basis(Gp(k),i,test_basis_type,test_derivative)*h_local^(-test_derivative)...
                                                       *reference_basis(Gp(k),j,trial_basis_type,trial_derivative)*h_local^(-trial_derivative);
                
            end
        end
    end

    result(:,:,n) = inv_a*result(:,:,n);

end